# @package _global_

half: True
grad_scaler: False
device: 'cuda:0'
seed: 2525
progress_bar: False
compile: 'trace'  # 'trace' or 'script' or 'script-with-example' or 'compile' or 'nothing'
compile_args:
  fullgraph: False
  dynamic:
  backend: "inductor"
  mode:
  options:
  disabled: False

save_model: False
save_interval: 10

epochs: 400
val_every: 1
es_patience: 100000
es_min_delta: 0.0001
es_metric: 'Train/Loss'
scheduler_metric: 'Train/Loss'
optimized_metric: "Val/Accuracy"