# @package metrics

Accuracy:
  parameters:
  aggregator: 'mean'
  levels: ['batch']
  higher_is_better: true

crossentropyloss:
  parameters:
  aggregator: 'mean'
  levels: ['batch']
  higher_is_better: False