# @package metrics

"Model Norm":
  parameters:
    norm_type: 2
  aggregator:
  levels: ['epoch']

"Learning Rate":
  parameters:
  aggregator:
  levels: ['batch', 'epoch']

"Batch Size":
  parameters:
  aggregator:
  levels: ['batch', 'epoch' ]
