# @package metrics

#"Model Norm":
#  parameters:
#    norm_type: 2
#  aggregator:
#  levels: ['batch']

"Learning Rate":
  parameters:
  aggregator:
  levels: ['batch']

"Batch Size":
  parameters:
  aggregator:
  levels: ['batch' ]
