# @package transformations

ImageRandomCrop:
  size: 32
  padding: 4
  apply_to: 'input'

ImageRandomHorizontalFlip:
  apply_to: 'input'

ImageToTensor:
  apply_to: 'input'

OneHot:
  num_classes: 100
  apply_to: 'target'

# RandAugment:
#   N: 2
#   M: 8
#   std: 0.5
#   apply_to: 'input'

# RandomErasing:
#   min_area: 0.05
#   max_area: 0.15
#   apply_to: 'input'

ImageNormalize:
  mean: [0.5071, 0.4867, 0.4408]
  std: [0.2675, 0.2565, 0.2761]
  apply_to: 'input'
