# @package transformations

ImageToTensor:
  apply_to: 'input'

OneHot:
  num_classes: 100
  apply_to: 'target'

ImageNormalize:
  mean: [0.5071, 0.4867, 0.4408]
  std: [0.2675, 0.2565, 0.2761]
  apply_to: 'input'
